[build]
  publish = "dist"          # 빌드 결과물이 담긴 폴더 (vite 기본 dist)
  command = "npm run build" # 빌드 명령어

[[redirects]]
  from = "/api/*"
  to = "http://ec2-13-125-34-183.ap-northeast-2.compute.amazonaws.com/:splat"
  status = 200
  force = true
  proxy = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

